### ISSUE TITLE
Task list

### ISSUE THREAD

**Issue by kty990** [kty990/createx#1]
- [ ] Build save file functionality -> Only testing left
- [x] Save functionality (.amk file)
- [ ] Components
    + ~~Square~~ -> Not doing this
    + ~~Radio Button~~ -> Not doing this, combined in with `Input`
    + ~~Normal Button~~
    + ~~Checkbox~~ -> Not doing this, combined in with `Input`
    + ~~Progress Bar~~
    + Dropdown Menu -> Still needs dropdown item saving and customization properties added
    + ~~Text~~
    + List view
        ^ Horizontal
        ^ Vertical
        ^ Sorted vs. Unsorted
    + Image -> Mostly complete. Requires some fine tuning for the file-src property
    + Video
    + ~~Input~~ -> Allows different file types, selected using dropdown
    + Links -> Needs on hover, on click, after visit, etc. properties
- [ ] Toolbars
    + ~~File bar~~ -> Functionality and more options added as needed
    + Animation bar
    + Quick action bar
- [x] Graphical hierarchical editing -> Example in heirarchy.js
- [x] ~~Auto-linking css and js to html on export~~ -> Part of build process
- [ ] Animation engine for 2D animations
- [ ] "Custom React" ->> Groups of components saved as singular component in component library
